# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 'Further Genealogy Research Notes'
author: Kurt Krueckeberg
#logo:  Prefer the PyDatat theme settings of image_light and image_dark
# used at the bottom of this file. 

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
# latex:
#  latex_documents:
#    targetname: book.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - bueckeburg-docs.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/kurt-krueckeberg/sphinx-research
# path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx_inline_tabs
    - linuxdoc.rstFlatTable
    - sphinx_external_toc
    - sphinx.ext.intersphinx
    - sphinx_design

  config:
    external_toc_exclude_missing: true
    intersphinx_mapping: 
      genealogy:
        - "https://gen.krueckeberg.org/"
        - "https://gen.krueckeberg.org/objects.inv"
      nla:
        - "https://nla.krueckeberg.org/"
        - null
      ancestry:
        - "https://anc.krueckeberg.org/"
        - null  

    myst_enable_extensions:
      - colon_fence
      - deflist
      - substitution
      - attrs_inline

    nitpicky: true

  # templates_path:
  #   - _templates

    exclude_patterns:
      - _build
      - Thumbs.db
      - .DS_Store 
      - .venv

    html_static_path:
      - _static

    html_css_files:
      - overrides.css

    html_js_files:
      - clickable-images.js

    html_theme_options:
      home_page_in_toc: true
      use_download_button: true

#     logo:
#       image_light: _static/myst-style-light-bueckeburg-archive.svg
#       image_dark: _static/myst-style-dark-bueckeburg-archive.svg
